variable "alb-name" {}
variable "load_balancer_type" {}
variable "public_subnet_id-a" {}
variable "public_subnet_id-b" {}
variable "public_subnet_id-c" {}
variable "target_type" {}
variable "alb-tg" {}
variable "vpc_id" {}
variable "instance-id" {}